red-hat-data-services/odh-dashboard

.env
README.md
backend/package.json
frontend/package.json
frontend/src/app/NavSidebar.tsx
frontend/src/redux/actions/actions.ts
package.json

Updates README and package.json files to reference the downstream repo.

Update upstream references

---

frontend/config/webpack.common.js
frontend/config/webpack.dev.js
frontend/config/webpack.prod.js
frontend/package-lock.json
frontend/package.json
frontend/src/app/App.tsx
frontend/src/app/QuickStarts.tsx
frontend/src/app/Routes.tsx
frontend/src/index.tsx
frontend/src/quickstarts/create-jupyter-notebook-quickstart.yaml
frontend/src/quickstarts/deploy-python-model-quickstart.yaml
frontend/src/typings.d.ts
frontend/src/utilities/NavData.ts

Adds quick stars drawer and catalog to ODH

Initial quick starts

---

backend/package.json
frontend/package-lock.json
frontend/package.json
package.json

Fix names for the packages in package.json's
Bump frontend's use of node-gyp to the latest version.

Update package names and bump up frontend node-gyp version

---

data/quickstarts/anaconda-ce-create-jupyter-notebook-quickstart.yaml

Looking for feedback on this format for an Anaconda CE quickstart

Added a quickstart for Anaconda

---

data/quickstarts/deploy-watson-model-quickstart.yaml
data/quickstarts/seldon-depploy-canaray-quickstart.yaml

/PTAL @jeff-phillips-18 @sophwats

added watson quick start

---

data/quickstarts/deploy-watson-model-quickstart.yaml

/PTAL @jeff-phillips-18 .  I made a few minor updates to the watson quick start content.

updated watson quickstart

---

data/quickstarts/anaconda-ce-create-jupyter-notebook-quickstart.yaml
data/quickstarts/deploy-watson-model-quickstart.yaml

Updated a typo in anaconda quick start

---

frontend/src/components/DocCardBadges.tsx
frontend/src/components/OdhCard.scss
frontend/src/components/OdhDocCard.tsx
frontend/src/pages/learningCenter/learningCenterUtils.ts
frontend/src/utilities/quickStartUtils.ts

Fixes https://github.com/red-hat-data-services/odh-dashboard/issues/23

Updates to cards in Resources section

---

data/applications/pachyderm.yaml
frontend/src/components/OdhAppCard.tsx
frontend/src/components/OdhCard.scss
frontend/src/components/OdhExploreCard.tsx
frontend/src/components/SupportedAppTitle.tsx
frontend/src/pages/enabledApplications/EnabledApplications.scss

Fixes https://github.com/red-hat-data-services/odh-dashboard/issues/22

Add star-check icon to Explore page

---

data/applications/pachyderm.yaml

Fixes https://github.com/red-hat-data-services/odh-dashboard/issues/30
cc @taneem-ibrahim

Set Pachyderm to Coming Soon

---

data/applications/starburst.yaml
data/applications/watson-studio.yaml
data/getting-started/pachyderm.md
data/getting-started/starburst.md
data/getting-started/watson-studio.md
data/quickstarts/anaconda-ce-create-jupyter-notebook-quickstart.yaml
data/quickstarts/deploy-watson-model-quickstart.yaml

PTAL @jeff-phillips-18  Thank you!

Added Starburst Content

---

.github/workflows/pull_request.yml
frontend/package.json

chore(build): action cache, limit frontend to lint

---

data/quickstarts/anaconda-ce-create-jupyter-notebook-quickstart.yaml
data/quickstarts/connect-rhosak-notebook-quickstart.yaml
data/quickstarts/create-jupyter-notebook-quickstart.yaml
data/quickstarts/deploy-python-model-quickstart.yaml
data/quickstarts/deploy-watson-model-quickstart.yaml
data/quickstarts/openvino-inference-notebook.yaml
data/quickstarts/seldon-deploy-canary-quickstart.yaml
data/quickstarts/seldon-deploy-drift-quickstart.yaml
data/quickstarts/seldon-deploy-explainer-quickstart.yaml
data/quickstarts/seldon-deploy-outlier-quickstart.yaml
frontend/package-lock.json
frontend/package.json
frontend/src/app/App.scss
frontend/src/components/DocCardBadges.tsx
frontend/src/components/OdhDocCard.tsx
frontend/src/components/OdhDocListItem.tsx
frontend/src/components/OdhListItem.scss
frontend/src/pages/learningCenter/LearningCenter.scss
frontend/src/pages/learningCenter/LearningCenter.tsx
frontend/src/pages/learningCenter/LearningCenterFilter.scss
frontend/src/pages/learningCenter/LearningCenterFilters.tsx
frontend/src/pages/learningCenter/LearningCenterListHeader.tsx
frontend/src/pages/learningCenter/const.ts
frontend/src/pages/learningCenter/learningCenterUtils.ts
frontend/src/types.ts
frontend/src/utilities/const.ts
frontend/src/utilities/utils.ts

**Fixes**: 
https://issues.redhat.com/browse/RHODS-753
As a DS user, I want to view my dashboard items in a list view rather than a card view in order to see more items at one time without scrolling.
Adds a list view options to the resources view. User can sort by clicking on column headers. User's preference is stored in local storage
**Screen shots / Gifs for design review**: 
**Browser conformance**:

Add List View option to resources view.

---

backend/src/types.ts
backend/src/utils/features.ts
backend/src/utils/resourceUtils.ts

Merge upstream to pickup changes to show notebook names in build notifications and for feature flag enablement.

Merge from upstream to pickup recent fixes

---

backend/src/routes/api/validate-isv/index.ts
backend/src/routes/api/validate-isv/validateISV.ts
backend/src/types.ts
frontend/src/pages/exploreApplication/EnableModal.scss
frontend/src/pages/exploreApplication/EnableModal.tsx
frontend/src/pages/exploreApplication/ExploreApplications.scss
frontend/src/types.ts

Jira: https://issues.redhat.com/browse/RHODS-748 (partially)
Simple cherry pick from upstream. No conflicts.

Cherry-Pick: Add ability to manually flag an app as enabled (#75)

---

frontend/src/components/OdhDocListItem.tsx
frontend/src/pages/learningCenter/LearningCenter.scss

Jira: https://issues.redhat.com/browse/RHODS-1078
Simple cherry-pick, no conflicts.

Cherry-Pick: Fix list view access label for tutorials, column widths. (#77)

---

backend/src/routes/api/components/list.ts
backend/src/types.ts
backend/src/utils/componentUtils.ts
backend/src/utils/resourceUtils.ts

**Fixes**: 
Jira: https://issues.redhat.com/browse/RHODS-750
Jira: https://issues.redhat.com/browse/RHODS-245
Simple cherry-pick.

Cherry-pick: Allow use of ConsoleLinks for route determination. (#78)

---

backend/src/routes/api/components/list.ts
backend/src/routes/api/validate-isv/validateISV.ts
backend/src/types.ts
backend/src/utils/componentUtils.ts

Jira: https://issues.redhat.com/browse/RHODS-600 (partial)
Simple cherry-pick, no conflicts.

Cherry-pick: Add enablement via CustomResource (#80)

---

data/applications/rhoam.yaml
data/getting-started/rhoam.md

Jira: https://issues.redhat.com/browse/RHODS-598

Updated RHOAM links.

---

data/quickstarts/seldon-deploy-canary-quickstart.yaml
data/quickstarts/seldon-deploy-drift-quickstart.yaml
data/quickstarts/seldon-deploy-explainer-quickstart.yaml
data/quickstarts/seldon-deploy-outlier-quickstart.yaml

Fixing Seldon Quickstarts with correct links for version 1.2

Update Seldon Quickstarts

---

frontend/src/__tests__/ExploreApplications.spec.tsx
frontend/src/components/OdhExploreCard.tsx
frontend/src/pages/exploreApplication/EnableModal.tsx
frontend/src/pages/exploreApplication/EnableVariable.tsx
frontend/src/pages/exploreApplication/ExploreApplications.tsx
frontend/src/pages/exploreApplication/GetStartedPanel.tsx

Simple cherry-pick of https://github.com/opendatahub-io/odh-dashboard/pull/84, no conflicts

Cherry-Pick: Persist enable modal status while in progress

---

data/quickstarts/deploy-model-rhoam-quickstart.yaml

Jira: https://issues.redhat.com/browse/RHODS-1597

Added RHOAM quickstart text

---

.env.production
frontend/src/app/App.scss
frontend/src/utilities/useWatchDashboardConfig.tsx

Simple cherry pick of https://github.com/opendatahub-io/odh-dashboard/pull/85, no conflicts

Cherry-Pick: Fix to quick start scrolling

---

backend/src/types.ts
backend/src/utils/resourceUtils.ts
frontend/src/types.ts
frontend/src/utilities/useWatchBuildStatus.tsx

Fixes: https://issues.redhat.com/browse/RHODS-1649
Simple cherry pick of https://github.com/opendatahub-io/odh-dashboard/pull/86, no conflicts

Cherry-Pick: Fixes for current image build status determination 

---

frontend/src/app/App.scss

Fixes: https://issues.redhat.com/browse/RHODS-1549
Simple cherry-pick of https://github.com/opendatahub-io/odh-dashboard/pull/87, no conflicts

Update contrast for the un-favorited favorite icon. (#87)

---

backend/src/routes/api/validate-isv/validateISV.ts

UPSTREAM: Fix for ISV enablement failure due to unsuspend cronjob failure

---

data/docs/seldon-model-servings-tutorial.yaml
data/docs/seldon-operational-tasks-how-to.yaml
data/getting-started/seldon-deploy.md
data/quickstarts/seldon-deploy-outlier-quickstart.yaml

Jiras:
https://issues.redhat.com/browse/RHODS-1807
https://issues.redhat.com/browse/RHODS-1813
https://issues.redhat.com/browse/RHODS-1814
Some fixes to Seldon Docs
```
https://github.com/red-hat-data-services/odh-dashboard/blob/master/data/getting-started/seldon-deploy.md
- Second/Third links broken
https://github.com/red-hat-data-services/odh-dashboard/blob/master/data/quickstarts/seldon-deploy-outlier-quickstart.yaml#L16
- (Outlier Detection)[https://deploy.seldon.io/en/v1.2/contents/demos/seldon-core/outlier-detection/index.html]
should be ==> [Outlier Detection](https://deploy.seldon.io/en/v1.2/contents/demos/seldon-core/outlier-detection/index.html)
https://github.com/red-hat-data-services/odh-dashboard/blob/master/data/docs/seldon-model-servings-tutorial.yaml#L12
- link broken …
```

Fix Seldon Docs

---

data/quickstarts/connect-rhosak-notebook-quickstart.yaml

RHODS-1828 - Update RHOSAK quick start to include topic info.

---

data/quickstarts/connect-rhosak-notebook-quickstart.yaml

RHODS-1828 - Update to text for Kafka QS to clarify topics tab

---

data/quickstarts/connect-rhosak-notebook-quickstart.yaml

RHODS-1828 - Move topic creation after SA creation

---

backend/src/routes/api/validate-isv/index.ts
backend/src/routes/api/validate-isv/validateISV.ts
frontend/src/services/validateIsvService.ts
frontend/src/utilities/useEnableApplication.tsx

FIxes: https://issues.redhat.com/browse/RHODS-1790
Simple cherry-pick of https://github.com/opendatahub-io/odh-dashboard/pull/93

[UPSTREAM] Fix validation timeout, poll for results

---

data/quickstarts/oneapi-aikit-notebook.yaml

Signed-off-by: Abolfazl Shahbazi <abolfazl.shahbazi@intel.com>
This is mostly to address some improvements suggested by `Red Hat` around `AiKit notebooks`.

Minor updates to the AiKit quickstart

---

data/quickstarts/openvino-inference-notebook.yaml

Fix step 3a not being recognized

---

data/getting-started/starburst.md

https://issues.redhat.com/browse/RHODS-2164

updated the beta text as per RHODS-2164

---

data/applications/pachyderm.yaml
data/docs/pachyderm-beginner-tutorial.yaml
data/getting-started/pachyderm.md

First version of Pachyderm Enablement Doc

---

frontend/src/components/OdhAppCard.tsx

RHODS 2243 fix for missing quickstart.

---

data/applications/starburst.yaml
frontend/src/pages/exploreApplication/GetStartedPanel.tsx

Update Starburst beta text

---

data/applications/anaconda-ce.yaml

Anaconda Commercial Edition description fix.

---

data/applications/openvino.yaml

Resolves https://issues.redhat.com/browse/RHODS-2730

Add ® to Intel in OpenVINO tile

---

data/applications/pachyderm.yaml
data/getting-started/pachyderm.md
data/quickstarts/pachyderm-beginner-tutorial-notebook.yaml

- [x ] The Jira story is acked
I submit this PR on behalf of nadegepepin from pachyderm team. This PR is the rebase version of PR#182

[Pachyderm] updated prerequisites section + Pachyderm deployment

---

backend/src/routes/api/cluster-settings/clusterSettingsUtils.ts
backend/src/types.ts
backend/src/utils/deployment.ts
frontend/src/pages/clusterSettings/ClusterSettings.scss
frontend/src/pages/clusterSettings/ClusterSettings.tsx
frontend/src/pages/clusterSettings/const.ts
frontend/src/services/clusterSettingsService.ts
frontend/src/types.ts
frontend/src/utilities/utils.ts

[UPSTREAM]: Add culler timeout feature and save button

---

data/applications/anaconda-ce.yaml
data/getting-started/anaconda-ce.md
data/quickstarts/anaconda-ce-create-jupyter-notebook-quickstart.yaml

Updating Anaconda product name from Commercial Edition to Professional

---

backend/src/routes/api/builds/index.ts
backend/src/routes/api/cluster-settings/index.ts
backend/src/routes/api/components/index.ts
backend/src/routes/api/config/index.ts
backend/src/routes/api/configmaps/index.ts
backend/src/routes/api/console-links/index.ts
backend/src/routes/api/docs/index.ts
backend/src/routes/api/getting-started/index.ts
backend/src/routes/api/gpu/index.ts
backend/src/routes/api/groups-config/groupsConfigUtil.ts
backend/src/routes/api/groups-config/index.ts
backend/src/routes/api/images/index.ts
backend/src/routes/api/nb-events/index.ts
backend/src/routes/api/notebooks/index.ts
backend/src/routes/api/notebooks/notebookUtils.ts
backend/src/routes/api/pvc/index.ts
backend/src/routes/api/quickstarts/index.ts
backend/src/routes/api/rolebindings/index.ts
backend/src/routes/api/secrets/index.ts
backend/src/routes/api/segment-key/index.ts
backend/src/routes/api/status/adminAllowedUsers.ts
backend/src/routes/api/status/index.ts
backend/src/routes/api/status/statusUtils.ts
backend/src/routes/api/validate-isv/index.ts
backend/src/types.ts
backend/src/utils/route-security.ts
backend/src/utils/userUtils.ts
frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx

Resolves: https://github.com/opendatahub-io/odh-dashboard/issues/487
Cherry pick of [upstream](https://github.com/opendatahub-io/odh-dashboard/pull/488)
Add additional security to routes to make sure they are requesting resources for them in the namespaces they expect to have.
See ticket

Rebuild for 1.16

---

backend/src/routes/api/notebooks/index.ts
backend/src/utils/route-security.ts

Add upstream commit added by https://github.com/opendatahub-io/odh-dashboard/pull/576 for the rhods-1.17 release

Pull in Sanitization Fix from downstream

---

backend/src/types.ts
backend/src/utils/route-security.ts

Pull in https://github.com/opendatahub-io/odh-dashboard/pull/583

Delete any envFrom sections from notebook containers. (#583)

---

backend/src/routes/api/notebooks/utils.ts
backend/src/typeHelpers.ts
backend/src/types.ts
backend/src/utils/notebookUtils.ts
backend/src/utils/route-security.ts
backend/src/utils/userUtils.ts
frontend/src/app/useApplicationSettings.tsx
frontend/src/pages/BYONImages/ImportImageModal.tsx
frontend/src/pages/BYONImages/UpdateImageModal.tsx
frontend/src/pages/clusterSettings/ClusterSettings.tsx
frontend/src/pages/exploreApplication/EnableVariable.tsx
frontend/src/pages/notebookController/screens/server/GPUSelectField.tsx
frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
frontend/src/pages/notebookController/screens/server/useGPUSetting.ts
frontend/src/services/notebookService.ts
frontend/src/types.ts
manifests/crd/odh-dashboard-crd.yaml

Added files for [RHODS-5593](https://issues.redhat.com/browse/RHODS-5593) and [RHODS-5569](https://issues.redhat.com/browse/RHODS-5569)

rhods 1.18 rebuild

---

backend/src/utils/prometheusUtils.ts

Add a fix for SSL issues when using DSG Prometheus calls.

Disable SSL warning for PVC prometheus call (#709)

---

backend/src/routes/api/envs/index.ts
backend/src/routes/api/groups-config/index.ts
backend/src/routes/api/notebooks/index.ts
backend/src/routes/api/status/index.ts
backend/src/utils/envUtils.ts
backend/src/utils/notebookUtils.ts
backend/src/utils/userUtils.ts

Fixing https://issues.redhat.com/browse/RHODS-5593

Fix Oauth Error, now catching the status code

---

frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
frontend/src/pages/notebookController/screens/server/StopServerModal.tsx
frontend/src/services/notebookService.ts
frontend/src/types.ts

* Omitted username field in spawner page for regular calls, as it should only be used when impersonating

Fix bug that prevented regular users to spawn notebooks (#836)

---

.gitignore
backend/src/app.ts
backend/src/routes/api/gpu/index.ts
backend/src/routes/api/k8s/index.ts
backend/src/routes/api/namespaces/index.ts
backend/src/routes/api/prometheus/index.ts
backend/src/utils/constants.ts
backend/src/utils/fileUtils.ts
backend/src/utils/route-security.ts

* Add admin activity logging
Signed-off-by: Landon LaSmith <LLaSmith@redhat.com>
* Reduce risk of perf issues with added logging
---------
Signed-off-by: Landon LaSmith <LLaSmith@redhat.com>
Co-authored-by: Maros Roman <mroman@redhat.com>
Co-authored-by: Andrew Ballantyne <8126518+andrewballantyne@users.noreply.github.com>

Admin logging (#914)

---

README.md

Bring changes from upstream:
- https://issues.redhat.com/browse/RHODS-6538
- https://issues.redhat.com/browse/RHODS-6792
- https://issues.redhat.com/browse/RHODS-7035

Update to rhods 1.23

---

frontend/src/pages/modelServing/useModelMetricsEnabled.ts

Removing Model Metrics from RHODS.
Removal of https://issues.redhat.com/browse/RHODS-6058

Disable Model Metrics

---

README.md

Release MR including this jira issues:
https://issues.redhat.com/browse/RHODS-6435
https://issues.redhat.com/browse/RHODS-6669
https://issues.redhat.com/browse/RHODS-6664
https://issues.redhat.com/browse/RHODS-6112
https://issues.redhat.com/browse/RHODS-6420
https://issues.redhat.com/browse/RHODS-6897
https://issues.redhat.com/browse/RHODS-1968
https://issues.redhat.com/browse/RHODS-6281

Prepare rhods 1.24

---

CONTRIBUTING.md
README.md
backend/src/types.ts
backend/src/utils/notebookUtils.ts
docs/dashboard_config.md
frontend/src/__mocks__/mockDashboardConfig.ts
frontend/src/__mocks__/mockNotebookK8sResource.ts
frontend/src/__mocks__/mockServingRuntimeK8sResource.ts
frontend/src/pages/modelServing/screens/projects/ServingRuntimeList.stories.tsx
frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx
frontend/src/pages/projects/screens/detail/ProjectDetails.stories.tsx
frontend/src/pages/projects/screens/detail/notebooks/useNotebookDeploymentSize.ts
frontend/src/utilities/valueUnits.ts
manifests/crd/odhdashboardconfigs.opendatahub.io.crd.yaml

Follow up of #270 
* https://issues.redhat.com/browse/RHODS-7795

Prepare 1.25 build (II)

---

frontend/src/pages/pipelines/global/pipelines/GlobalNoPipelines.tsx

Update the visual text on the empty Pipeline state.
https://issues.redhat.com/browse/RHODS-8373

Update the visual editor wording

---

frontend/src/utilities/clusterUtils.ts

https://issues.redhat.com/browse/RHODS-8465
Just setting this PR up now -- waiting to see if this actually becomes a blocker for 1.27.

OpenShift Console link fixes (#1231)

---

frontend/src/concepts/pipelines/context/useManageElyraSecret.ts
frontend/src/concepts/pipelines/elyra/utils.ts

Hotfix 
- https://issues.redhat.com/browse/RHODS-9443
- https://issues.redhat.com/browse/RHODS-9447

Switch to Kubernetes secret instead of users credentials (#1416)

---

frontend/src/concepts/pipelines/context/useManageElyraSecret.ts
frontend/src/concepts/pipelines/elyra/const.ts
frontend/src/concepts/pipelines/elyra/utils.ts

Additional fix for https://issues.redhat.com/browse/RHODS-9443

Update Existing Elyra Secret if incorrect (#1419)

---

frontend/src/__mocks__/mockRouteK8sResource.ts
frontend/src/__mocks__/mockServingRuntimeK8sResource.ts
frontend/src/__tests__/integration/pages/modelServing/ModelServingGlobal.spec.ts
frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.spec.ts
frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.stories.tsx
frontend/src/__tests__/integration/pages/projects/ProjectDetails.stories.tsx
frontend/src/concepts/pipelines/content/createRun/const.ts
frontend/src/concepts/pipelines/context/useManageElyraSecret.ts
frontend/src/concepts/pipelines/elyra/const.ts
frontend/src/concepts/pipelines/elyra/utils.ts
frontend/src/pages/modelServing/customServingRuntimes/utils.ts
frontend/src/pages/projects/components/DeleteModal.tsx

Jira Links:
- https://issues.redhat.com/browse/RHODS-8870
- https://issues.redhat.com/browse/RHODS-9064
- https://issues.redhat.com/browse/RHODS-9278
- https://issues.redhat.com/browse/RHODS-9329
- https://issues.redhat.com/browse/RHODS-7928
- https://issues.redhat.com/browse/RHODS-7490 
- https://issues.redhat.com/browse/RHODS-6446
- https://issues.redhat.com/browse/RHODS-9443 
- https://issues.redhat.com/browse/RHODS-9512

Prepare 1.29 release

---

frontend/src/__mocks__/mockServingRuntimeTemplateK8sResource.ts
manifests/base/role.yaml

In the dashboard:
1. Go to Settings - Serving Runtimes
2. Click “Add new”
3. Check that you can create a new Serving Runtime
4. Try to edit it
5. Try to delete it

Add permissions for templates and serving runtimes (#1466)

---

.github/ISSUE_TEMPLATE/bug_report.yaml
frontend/src/__tests__/integration/pages/modelServing/ModelServingGlobal.spec.ts
frontend/src/api/pipelines/custom.ts
frontend/src/concepts/pipelines/apiHooks/usePipelineRunsForPipeline.ts
frontend/src/concepts/pipelines/const.ts
frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineDetails.tsx
frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineNotFound.tsx
frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetails.tsx
frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunTabDetails.tsx
frontend/src/concepts/pipelines/content/tables/pipeline/PipelinesTable.tsx
frontend/src/concepts/pipelines/content/tables/pipeline/PipelinesTableExpandedRow.tsx
frontend/src/concepts/pipelines/content/tables/pipeline/PipelinesTableRow.tsx
frontend/src/concepts/pipelines/content/tables/pipeline/expandedRowRenderUtils.tsx
frontend/src/concepts/pipelines/content/tables/utils.ts
frontend/src/concepts/pipelines/context/useManageElyraSecret.ts
frontend/src/concepts/pipelines/elyra/const.ts
frontend/src/concepts/pipelines/elyra/utils.ts
frontend/src/concepts/pipelines/types.ts
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/InferenceServiceFrameworkSection.tsx
frontend/src/pages/projects/screens/detail/pipelines/PipelinesList.tsx
frontend/src/pages/projects/screens/projects/EmptyProjects.tsx
frontend/src/pages/projects/screens/projects/ProjectListView.tsx

Release Notes: https://github.com/opendatahub-io/odh-dashboard/releases/tag/v2.13.0
* https://issues.redhat.com/browse/RHODS-9374
* https://issues.redhat.com/browse/RHODS-9244
* https://issues.redhat.com/browse/RHODS-8366
* https://issues.redhat.com/browse/RHODS-8066
* https://issues.redhat.com/browse/RHODS-7982
* https://issues.redhat.com/browse/RHODS-9788
* https://issues.redhat.com/browse/RHODS-8909

RHODS 1.30 Sync

---

backend/src/utils/resourceUtils.ts

Fix blocker issue https://issues.redhat.com/browse/RHODS-9991
1. Get the annotation opendatahub.io/template-enabled one one of the templates.
2. Reload the dashboard pod
3. Check that the first status object doesn't return status in DashboardConfig

Fix issue when doing first migration of the dashboard config

---

frontend/src/app/App.tsx
frontend/src/components/GenericSidebar.tsx
frontend/src/utilities/const.ts
frontend/src/utilities/utils.ts

https://issues.redhat.com/browse/RHODS-12054

update scroll container selector for JumpLinks

---

frontend/src/k8sTypes.ts
frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeTableRow.tsx
frontend/src/services/templateService.ts
frontend/src/types.ts
frontend/src/utilities/__tests__/addTypesToK8sListedResources.spec.ts
frontend/src/utilities/addTypesToK8sListedResources.ts
frontend/src/utilities/useAcceleratorState.ts

Follow up on https://github.com/red-hat-data-services/odh-dashboard/pull/299
One more PR merged before the release was created upstream, so best to just sync up RHODS with it.

Last min sync for 1.34

---

backend/src/utils/constants.ts
docs/dashboard-config.md
frontend/src/__mocks__/mockDashboardConfig.ts
frontend/src/__tests__/integration/pages/customServingRuntimes/CustomServingRuntimes.spec.ts
frontend/src/pages/modelServing/screens/projects/ModelServingPlatformSelect.tsx
manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml

Pull in the fix for https://issues.redhat.com/browse/RHOAIENG-126 from the upstream repo.

Enable modelmesh on cluster creation

---

frontend/src/__tests__/cypress/cypress/e2e/modelServing/ModelMetrics.cy.ts
frontend/src/api/models/trustyai.ts

Merges the trusty change in CR for GA.

Sync 2.6 with last change.

---

backend/src/routes/api/proxy/index.ts
backend/src/routes/wss/k8s/index.ts
backend/src/server.ts
backend/src/utils/directCallUtils.ts
backend/src/utils/httpUtils.ts
backend/src/utils/prometheusUtils.ts
manifests/base/deployment.yaml

Cherry pick of https://github.com/opendatahub-io/odh-dashboard/pull/2555 targeted to 2.8 RC3
https://issues.redhat.com/browse/RHOAIENG-2380

Rhoai 2.8 rc3

---

frontend/src/app/AppLauncher.tsx

Closes: https://issues.redhat.com/browse/RHOAIENG-4490
Cherry-pick of https://github.com/opendatahub-io/odh-dashboard/pull/2564

Fix for application launcher crash

---

manifests/overlays/modelserving/kustomization.yaml

Update TGIS image to address https://issues.redhat.com/browse/RHOAIENG-4329 ONNX vuln fix

Update TGIS to address RHOAIENG-4329

---

manifests/overlays/modelserving/kustomization.yaml

Closes:
https://issues.redhat.com/browse/RHOAIENG-6393
https://issues.redhat.com/browse/RHOAIENG-5508

Update both TGIS and Caikit-TGIS images for RHOAI 2.8.2

---

frontend/src/__mocks__/mockImageStreamK8sResource.ts
frontend/src/__mocks__/mockNotebookK8sResource.ts
frontend/src/__tests__/cypress/cypress/e2e/projects/projectDetails.cy.ts
frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
frontend/src/pages/projects/screens/detail/notebooks/__tests__/useNotebookImageData.spec.ts
frontend/src/pages/projects/screens/detail/notebooks/useNotebookImageData.ts

https://issues.redhat.com/browse/RHOAIENG-7932
cc @atheo89

Internal registry rhoai 2.8.3

---

manifests/overlays/modelserving/kustomization.yaml

Jira : https://issues.redhat.com/browse/RHOAIENG-10001

Update TGIS image SHA

---

manifests/overlays/modelserving/kustomization.yaml

Update TGIS SHA

---

backend/src/routes/api/nim-serving/index.ts
frontend/src/api/k8s/servingRuntimes.ts
frontend/src/pages/modelServing/screens/projects/NIMServiceModal/DeployNIMServiceModal.tsx
frontend/src/pages/modelServing/screens/projects/NIMServiceModal/NIMModelListSection.tsx
frontend/src/pages/modelServing/screens/projects/__tests__/utils.spec.ts
frontend/src/pages/modelServing/screens/projects/nimUtils.ts
frontend/src/pages/modelServing/screens/projects/utils.ts

https://issues.redhat.com/browse/RHOAIENG-13874

Config map nim model name fetch (#3276) (#3290)

---

backend/package-lock.json
backend/package.json
frontend/package-lock.json

This PR fixes 2 CVEs:
https://issues.redhat.com/browse/RHOAIENG-12612
https://issues.redhat.com/browse/RHOAIENG-13432

Several CVE fixes for RHOAI 2.13.1

---

Dockerfile.konflux

This PR addresses: #https://issues.redhat.com/browse/RHOAIENG-14049

Review Dockerfile changes for building odh-dashboard in Konflux

---

Dockerfile.konflux

Part of https://issues.redhat.com/browse/RHOAIENG-14049

Change user to UID

---

frontend/src/components/SimpleSelect.tsx
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/InferenceServiceFrameworkSection.tsx
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx

JIRA: https://issues.redhat.com/browse/RHOAIENG-15526
Merge the fixes to the blocker issue into rhoai-2.16 branch.

[RHOAI 2.16] Make SimpleSelect one-option hook triggered on key instead of the options

---

.tekton/odh-dashboard-v2-16-push.yaml

Update rhoai version 2.16.1

---

Dockerfile.konflux

https://issues.redhat.com/browse/RHOAIENG-18496

Add Dockerfile.konflux for 2.8

---

frontend/.env

Dashboard upversion release (#3704)

---

frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelinesTopology.cy.ts
frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx

[RHOAIENG-18916](https://issues.redhat.com/browse/RHOAIENG-18916)

[Backport] Pipeline logs are not appearing on run details page (#3740)

---

backend/src/utils/constants.ts
docs/dashboard-config.md
frontend/src/__mocks__/mockDashboardConfig.ts
frontend/src/__mocks__/mockNimResource.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/modelServingNim.cy.ts
frontend/src/components/OdhAppCard.tsx
frontend/src/concepts/areas/const.ts
frontend/src/pages/modelServing/screens/projects/NIMServiceModal/ManageNIMServingModal.tsx
frontend/src/pages/modelServing/screens/projects/ProjectModelMetricsPage.tsx
frontend/src/utilities/useEnableApplication.tsx
manifests/rhoai/shared/odhdashboardconfig/odhdashboardconfig.yaml

https://issues.redhat.com/browse/NVPE-157
https://issues.redhat.com/browse/NVPE-145
https://issues.redhat.com/browse/NVPE-101
https://issues.redhat.com/browse/NVPE-133
https://issues.redhat.com/browse/NVPE-136
* fix: set disableNIMModelServing to false as required for GA (#3747)
* fix: show backend error message for API key validation instead of hardcoded message (#3748)
* fix: set default Model Server size to 'Custom' and update helper text (#3727)
* fix: set default Model Server size to 'Custom' and update helper text
* fix: update resource values for 'Custom' option
* fix: update nim cypress test
* fix: update nim cypress test
---------
* Fix navigation issue: Add direct back link to models list from model metrics page (#3720)
* disable "Disabled" NIM Link for Non-Admins with Tooltip …

V2.31.0 fixes more nim stuff (#3763)

---

Dockerfile.konflux

Follow up of https://github.com/opendatahub-io/odh-dashboard/pull/3783
Upgrade base image to Node 20

Upgrade base image to Node 20

---

frontend/.env

Upversion Dashboard (#3931)

---

frontend/src/__mocks__/mockConnectionType.ts
frontend/src/__tests__/cypress/cypress/pages/connections.ts
frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDeploy.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingGlobal.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/runtime/servingRuntimeList.cy.ts
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionSection.tsx
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx

* Filter out OCI connections
* Add OCI modelmesh cypress test

Filter out OCI connections for model mesh (#3946) (#3948)

---

manifests/common/connection-types/kustomization.yaml

Closes https://issues.redhat.com/browse/RHOAIENG-22043
The OCI ootb yaml isn't being applied in the latest odh dashboard manifests. Without this, OCI will not be enabled / available
run `kustomize build common/connection-types` to check the process

Add oci to connection types Kustomization 2.19 cherry pick

---

.tekton/odh-dashboard-v2-19-push.yaml

required to pass conforma after 1 april

[KONFLUX-2264,RHOAIENG-22379] add sast tasks to konflux

---

.tekton/odh-dashboard-v2-20-push.yaml

[KONFLUX-2264,RHOAIENG-22432] add sast tasks to konflux

---

.tekton/odh-dashboard-v2-21-push.yaml
Dockerfile.konflux
install/konflux/package-lock.json
install/konflux/package.json
install/konflux/readme.txt

https://issues.redhat.com/browse/RHOAIENG-24700

Multi-Arch Pipeline Fix

---

frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionOciPathField.tsx

https://issues.redhat.com/browse/RHOAIENG-24886

Fix http prefix removal for OCI path (#4151)

---

Dockerfile.konflux.sealights

adding recommendations from sealights

update sealights dockerfile

---

Dockerfile.konflux

Bring the main fix for all the `esbuild` and hermeto issues.
Fix: https://issues.redhat.com/browse/RHOAIENG-25231

Bring 2.21 changes to main

---

Dockerfile.konflux

I've pretty much tested this locally, my way to go to test it was:
Create the branch based on `rhoai-2.21` (my origin is red-hat-data-service):
`git checkout -b fix-merge-conflict origin/rhoai-2.21`
Cherry pick the commit that was causing the conflict:
`git cherry-pick 8b6c49df8bb50f6472ab1e14eaab68ac30686c1b`
Resolve the issues and continue:
```bash
git add .
git cherry-pick --continue
```
Merge the new branch to `rhoai-2.21`:
```bash
git switch rhoai-2.21   
git merge fix-merge-conflict
```
Now try to merge main (you need to have main update with red-hat-data-service main):
```bash
git merge main
```
-------------------
**If you try only mergin main to rhoai-2.21 you'll get a merge conflict, that's how you know this is working**
I think the git log is correct with this flow:
```bash …
```

Resolve merge conflicts

---

frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionOciPathField.tsx

https://issues.redhat.com/browse/RHOAIENG-24967

Fix http prefix removal for OCI path (#4150) (#4294)

---

Dockerfile.konflux.sealights

odh dashboard failed to run with sealights due to missing token and bsid
built and ran locally
should allow testing with sealights

fix: BSID and SL_TOKEN in container image

---

Dockerfile.konflux.sealights

comment find an replace

---

Dockerfile.konflux.sealights

Use new SL agent 1069 and remove find&replace command

---

Dockerfile.konflux.sealights

simplify download of specific slnodejs version

---

frontend/.env
manifests/common/crd/hardwareprofiles.opendatahub.io.crd.yaml
manifests/common/crd/kustomization.yaml

https://issues.redhat.com/browse/RHOAIENG-30246
patch blocker issue
n/a already tested
n/a

V2.36.0 fixes

---

manifests/common/crd/hardwareprofiles.opendatahub.io.crd.yaml
manifests/common/crd/kustomization.yaml

https://issues.redhat.com/browse/RHOAIENG-30321

Add fix to image streams notebook enabling label

---

frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testModelTokenAuth.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelAdminCreation.cy.ts

https://issues.redhat.com/browse/RHOAIENG-32615

Quarantine/Unquarantine workbench/distributed workload metrics test- cherry-pick

---

backend/src/routes/api/images/imageUtils.ts
backend/src/utils/notebookUtils.ts
frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/artifacts/__tests__/utils.spec.ts
frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/artifacts/utils.ts
manifests/core-bases/base/aggregate-permissions.rbac.yaml
manifests/core-bases/base/kustomization.yaml

from this PR https://github.com/opendatahub-io/odh-dashboard/pull/4769
This is a back port of 4 fixes
- https://issues.redhat.com/browse/RHOAIENG-31937
- https://issues.redhat.com/browse/RHOAIENG-28911
- https://issues.redhat.com/browse/RHOAIENG-31860
- https://issues.redhat.com/browse/RHOAIENG-31381
tests pass
n/a backport

V2.35.0 fixes

---

frontend/src/utilities/const.ts

Backporting for [RHOAIENG-29353](https://issues.redhat.com/browse/RHOAIENG-29353)
Upstream PR: https://github.com/opendatahub-io/odh-dashboard/pull/4807

Cherry-pick: Avoid destructuring from process.env (#4807)

---

frontend/src/concepts/distributedWorkloads/DistributedWorkloadsContext.tsx
frontend/src/concepts/distributedWorkloads/PermissionsNotSet.tsx

https://issues.redhat.com/browse/RHOAIENG-35104

2.24 dw fix (#5045)

---

.tekton/odh-dashboard-gen-ai-poc-push.yaml

update path context to root
