frontend/src/components/OdhAppCard.tsx
frontend/src/components/OdhExploreCard.tsx

Import of classnames as `ClassNames` works on mac, but not in the s2i builds.

Fix import of classnames

---

data/docs/auto-ai-experiment-model-tutorial.yaml
data/docs/build-binary-classification-model-tutorial.yaml
data/docs/jupyter-notebooks-in-watson-studio-tutorial.yaml
data/docs/python-notebook-generate-results-open-scale-tutorial.yaml

Add more watson tutorials

---

data/getting-started/seldon-deploy.md
data/quickstarts/seldon-deploy-canary-quickstart.yaml
data/quickstarts/seldon-deploy-drift-quickstart.yaml
data/quickstarts/seldon-deploy-explainer-quickstart.yaml
data/quickstarts/seldon-deploy-outlier-quickstart.yaml

Adding seldon demos for:
* explanations for model predictions
* outlier detection
* drift detection
Also adding to the getting started page to explain seldon deploy and how it leverages seldon core

more seldon quickstarts

---

frontend/src/app/App.scss
frontend/src/app/HeaderTools.tsx
frontend/src/images/odh-logo.svg
frontend/src/index.html

Fixes https://issues.redhat.com/browse/RHODS-501
Addresses https://issues.redhat.com/browse/RHODS-495
Uses an icon rather than text for the current user making it better by not showing `inClusterUser`.
/cc @kywalker-rh

Use standard user icon for user until we can get the real username. Fix html title.

---

backend/plugins/kube.js
backend/routes/api/components/componentUtils.js
backend/routes/api/components/list.js
backend/utils/watchInstalledOperators.js
backend/utils/watchServices.js

At startup, start fetching CSVs and Services every 2 minutes.
Cache these results and use them on queries rather than fetching them at query time (can be slow on large systems).

Periodically fetch CSVs and Services and cache results

---

data/docs/python-acceleration-numba-tutorial.yaml

This change fixes a typo in the description for the
python-accelerated-numba-tutorial tutorial widget.

Fix python-accelerated typo

---

data/applications/starburst.yaml
data/docs/jupyter-notebooks-in-watson-studio-tutorial.yaml
data/docs/seldon-model-servings-tutorial.yaml
data/docs/watson-studio-cleanse-shape-visualize-how-to.yaml
data/docs/watson-studio-create-deployment-space-how-to.yaml
data/docs/watson-studio-integrate-with-github-how-to.yaml
data/docs/watson-studio-load-data-how-to.yaml
data/docs/watson-studio-runtime-env-how-to.yaml
data/docs/watson-studio-setup-openscale-how-to.yaml
data/quickstarts/connect-rhosak-notebook-quickstart.yaml
data/quickstarts/deploy-python-model-quickstart.yaml
data/quickstarts/seldon-deploy-canary-quickstart.yaml
data/quickstarts/seldon-deploy-drift-quickstart.yaml
data/quickstarts/seldon-deploy-explainer-quickstart.yaml
data/quickstarts/seldon-deploy-outlier-quickstart.yaml

**Changes proposed in this pull request**
- 
- Fixing typos in the Resources widgest.
**Test instructions**
1. I've updated the description in /data/applications, so all the phrases end up in period.
**Closing issues**
1. Closes [RHODS-744](https://issues.redhat.com/browse/RHODS-744)
**Additional context**
1. It's my first PR, so I'm not sure if this is the proper way to open a change, please tell me the best practices to work with this project.

Fixed typos in resources description

---

backend/package-lock.json
frontend/package-lock.json
frontend/src/components/OdhCard.scss
frontend/src/components/OdhDocCard.tsx
frontend/src/pages/learningCenter/LearningCenter.tsx
frontend/src/utilities/useEventListener.ts
frontend/src/utilities/useLocalStorage.ts
package-lock.json

**Fixes**: 
https://issues.redhat.com/browse/RHODS-754
As a DS user, I want to be able to mark resources as favorites in order to quickly find those that I access frequently.
Adds a clickable favorite indicator to cards in the Resources view. Uses local storage to track favorite items. When sorting, sort favorites before non-favorites, then by selected sort. 
Also updated NPM version so it's now using `"lockfileVersion": 2,`
**Screen shots / Gifs for design review**: 
**Browser conformance**:

Add ability to 'favorite' resource cards.

---

backend/src/routes/api/status/index.ts
backend/src/types.ts

Since we use [OpenShift oauth-proxy](https://github.com/openshift/oauth-proxy#command-line-options) when the application is in a cluster, we can read the username directly from the headers `x-forwarded-user` field of the request that proxy transmits to the server.
This PR changes the `status` API to read the username and send it back to the front-end.

Get real username when in cluster

---

frontend/src/pages/learningCenter/LearningCenter.tsx
frontend/src/pages/learningCenter/LearningCenterFilters.tsx
frontend/src/pages/learningCenter/ProviderTypeFilters.tsx
frontend/src/pages/learningCenter/const.ts
frontend/src/pages/learningCenter/useDocFilterer.ts
frontend/src/types.ts

**Fixes**: 
Downstream should provide a filter for provider type
upstream does not show provider types and its not a concept upstream.
Add `Provider Type` to the available filters in the resources filter panel
**Screen shots / Gifs for design review**:

Add resources filter by provider type

---

data/quickstarts/deploy-python-model-quickstart.yaml

The template project sets the route at /predictions. This patch updates the quickstart accordingly 
https://github.com/opendatahub-io/odh-s2i-project-simple/blob/5af8a31d8c66a80a92289255d06fde33b709c76d/wsgi.py#L14

Amend route to 'predictions'

---

data/applications/openvino.yaml
data/docs/openvino-toolkit-ovms-serving.yaml
data/quickstarts/openvino-inference-notebook.yaml

**Fixes**: 
https://issues.redhat.com/browse/RHODS-858
https://issues.redhat.com/browse/RHODS-859
OpenVINO has gone GA so it is now available
Remove the feature flag requirement so that the OpenVINO card and resources are shown.
Check for the OpenVINO CSV being installed to determine if OpenVINO is enabled.
**Screen shots / Gifs for design review**: 
/cc @kywalker-rh

Add OpenVINO, add mechanism to check for enablement.

---

data/applications/rhosak.yaml

**Fixes**: 
Jira: https://issues.redhat.com/browse/RHODS-748
RHOSAK must use manual enablement to decide when to show in the Enabled page
Add the fields necessary to show the manual enable dialog
**Screen shots / Gifs for design review**:

Add manual enablement for RHOSAK

---

data/applications/rhoam.yaml

**Fixes**: 
Jira: https://issues.redhat.com/browse/RHODS-600
The RHOAM team has asked for a different mechanism for determining if RHOAM is enabled.
Determination should be made by checking for the existence of a CR with a field set to complete.
Add the CR details to the RHOAM application def file

Use RHMI CR to determine RHOAM enablement

---

.env

**Fixes**: 
Jira: https://issues.redhat.com/browse/RHODS-1530
Current doc link is not correct for GA
Update the doc link to https://access.redhat.com/documentation/en-us/red_hat_openshift_data_science

Update documentation link from dashboard for GA

---

backend/src/types.ts
backend/src/utils/resourceUtils.ts
frontend/src/app/HeaderTools.tsx
frontend/src/types.ts
frontend/src/utilities/useWatchDashboardConfig.tsx

Simple cherry-pick of https://github.com/opendatahub-io/odh-dashboard/pull/83, no conflicts

Cherry-pick: Add a dashboard config option to hide the support link

---

backend/src/utils/componentUtils.ts
data/applications/rhoam.yaml

https://issues.redhat.com/browse/RHODS-1656
cloud.redhat.com changed to console.redhat.com.
Getting started link was broken due to permissions, but we should log out errors to catch it.

Update link to cloud.rehat.com to console.redhat.com. Log errors when inspecting CR

---

data/applications/seldon.yaml

**Fixes**: 
Jira: https://issues.redhat.com/browse/RHODS-1658
Getting started link for Seldon Deploy changed
Update the getting started link for Seldon Deploy

Fix Seldon Deploy getting started link

---

backend/src/types.ts
backend/src/utils/resourceUtils.ts
frontend/src/app/App.scss
frontend/src/app/AppNotificationDrawer.tsx
frontend/src/redux/types.ts
frontend/src/types.ts
frontend/src/utilities/useWatchBuildStatus.tsx
install/odh/base/deployment.yaml

UPSTREAM: Fix to more accurately communicate build statuses

---

backend/src/routes/api/segment-key/segmentKeyUtils.ts
backend/src/utils/componentUtils.ts
data/applications/anaconda-ce.yaml

**Fixes**: 
Jira: https://issues.redhat.com/browse/RHODS-1866
The default quick start for Anaconda CE was not set in it's application definition yaml
Add the quick start to the app def. Also, add some expected failure checks to avoid flooding the logs with unnecessary false errors.

Add default quick start for Anaconda CE

---

data/quickstarts/seldon-deploy-drift-quickstart.yaml
frontend/src/app/App.scss

**Fixes**: 
Jira: https://issues.redhat.com/browse/RHODS-1893
Missing period at the end of the sentence describing the Seldon drift quick start
Also, dropdown item, menu items and button font sizes are not consistent w/ console.
Added the period at the end of the description.
Added the override for dropdown item, menu items and button font sizes to be consistent with console.

Fix for punctuation on Seldon drift quick start description

---

data/docs/python-gpu-numba-tutorial.yaml
data/features.json

**Fixes**: 
Jira: https://issues.redhat.com/browse/RHODS-1918
GPU selection is not available so  the tutorials about GPU computing (i.e., GPU Computing in Python with Numba) should be hidden in the "Resources" tab of RHODS 
Mark the `GPU Computing in Python with Numba` tutorial as requiring a feature flag of `gpu-computing` which is set to false.

Hide 'GPU Computing' tutorial behind a feature flag

---

backend/src/types.ts
backend/src/utils/resourceUtils.ts
frontend/src/app/AppLauncher.tsx
frontend/src/app/HeaderTools.tsx
frontend/src/types.ts
frontend/src/utilities/useWatchDashboardConfig.tsx

**Fixes**: 
Jira: https://issues.redhat.com/browse/RHODS-1945
The sandbox users will not have access to cluster management and therefore the link to Cluster manager console is useless.  
The dashboard only checks for the availability of the cluster manager it does not know if the user has access.
Add a config setting to disable access to the cluster manager.
Example config map with disablement:
```
kind: ConfigMap
apiVersion: v1
metadata:
name: odh-dashboard-config
namespace: redhat-ods-applications
uid: 3b8092d5-94b0-45d4-b010-1bd88e5968ff
resourceVersion: '100273'
creationTimestamp: '2021-09-24T12:37:29Z'
managedFields:
- manager: Mozilla
operation: Update
apiVersion: v1
time: '2021-09-24T12:37:29Z'
fieldsType: FieldsV1
fieldsV1: …
```

Add config option to disable access to cluster manager

---

data/applications/aikit.yaml
frontend/src/app/AppLauncher.tsx

**Fixes**: 
Jira:
https://issues.redhat.com/browse/RHODS-1818
https://issues.redhat.com/browse/RHODS-1819
AiKit was not ready and was hidden via a feature flag.
We did not know the CSV to look for in order to enable AiKit
Remove the feature flag and update the enablement mechanism
**Screen shots / Gifs for design review**:

Update AI Kit app def to not be feature flagged out

---

data/quickstarts/connect-rhosak-notebook-quickstart.yaml

Add service account permissions to Kafka quickstart

---

data/quickstarts/oneapi-aikit-notebook.yaml

Removes the extra scikit category.

RHODS-2213: Fix for extra scikit category.

---

frontend/src/pages/exploreApplication/ExploreApplications.tsx
frontend/src/pages/exploreApplication/GetStartedPanel.tsx

Track tile-usage on Explore tab

---

data/applications/watson-studio.yaml
data/features.json
data/quickstarts/deploy-watson-model-quickstart.yaml

FeatureFlagging Watson Studio since it is not compatible with OpenShift 4.9+ for now

---

data/applications/starburst.yaml
data/getting-started/starburst.md

set beta to false since starburst galaxy is now a GA offering

Remove Starburst Beta Text from the getting started

---

data/applications/watson-studio.yaml
data/features.json
data/quickstarts/deploy-watson-model-quickstart.yaml

- Revert "FeatureFlagging Watson Studio since it is not compatible with OpenShift 4.9+ for now"
- Revert "Hiding IBM Watson from Resources section of ODH"

revert 2883

---

frontend/src/pages/clusterSettings/ClusterSettings.tsx

Fix to allow a user to enter an empty string.

[UPSTREAM] Fix for input not allowing blank spaces.:

---

frontend/src/components/DocCardBadges.tsx
frontend/src/utilities/quickStartUtils.ts

Fix for in progress showing up incorrectly, along with fix for not showing failed if a quick start has been completed.
1.)  Failed status test:
- Go To RHODS Dashboard > Resources
- Start a quick start
- Click on each step and set "no" to the checkbox in the "Check your work" dialog
- Click on "Close" button 
- Check the QuickStart status on the card, make sure it says Failed.
2.)  Skip step - in progress test:
- Go To RHODS Dashboard > Resources
- Start a quick start
- Skip one or more step instead of selecting "yes" or "no" in the "Check your work" dialog.
- Select on each step and set "no" or "yes" on some steps in the "Check your work" dialog
- Click on "Close" button 
- Check the QuickStart status on the card, make sure it says In Progress.
- Click continue, then go back and complete …

[UPSTREAM] Fixed progress showing incorrectly for Quick Starts. (#206)

---

backend/src/routes/api/status/index.ts
backend/src/types.ts
backend/src/utils/componentUtils.ts
backend/src/utils/resourceUtils.ts
backend/src/utils/resourceWatcher.ts

**Testing:**  Operator performance test should be completed on a cluster with multiple installed operators and created resources for many users.  For this, https://github.com/codeready-toolchain/toolchain-e2e/tree/master/setup can be used to test kubeapi memory consumption.  Memory can be observed from test results and the on cluster metrics.  For regression testing, we must make sure the add-ons for AIKit, OpenVino, Pachyderm, Seldon, and Watson Studio are all still working. 
**(Updated) Live Build:** `quay.io/modh/rhods-operator-live-catalog:1.11.0-rhods-3191`

[UPSTREAM] Fix for CPU and Memory issues fetching resources

---

backend/src/types.ts
backend/src/utils/componentUtils.ts

Testing: 
Live Build: quay.io/modh/rhods-operator-live-catalog:1.11.0-rhods-4035
1. Create a bad subscription.  e.g:
```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
name: bad-sub
namespace: default
spec:
channel: alpha
installPlanApproval: Manual
name: bad-sub
source: redhat-operators
sourceNamespace: openshift-marketplace
```
2. Restart od-dashboard pods
3. Verify Enabled and Explore tabs are populated correctly

[UPSTREAM] Fix blank dashboard when a subscription without status or installedCSV exists.

---

backend/src/routes/api/groups-config/index.ts
backend/src/routes/api/health/healthUtils.ts
backend/src/routes/api/health/index.ts
backend/src/routes/api/nb-events/index.ts
backend/src/routes/api/notebooks/index.ts
backend/src/routes/api/notebooks/notebookUtils.ts
backend/src/routes/api/rolebindings/index.ts
backend/src/routes/api/route/index.ts
backend/src/routes/api/secrets/index.ts
backend/src/routes/api/status/index.ts
backend/src/utils/adminUtils.ts
backend/src/utils/requestUtils.ts
backend/src/utils/route-security.ts
backend/src/utils/userUtils.ts
frontend/package-lock.json
frontend/src/app/App.tsx
frontend/src/app/HeaderTools.tsx
frontend/src/app/appUtils.ts
frontend/src/pages/notebookController/SetupCurrentNotebook.tsx
frontend/src/pages/notebookController/notebookControllerContextTypes.ts
frontend/src/pages/notebookController/screens/server/NotebookServer.tsx
frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
frontend/src/pages/notebookController/screens/server/StartServerModal.tsx
frontend/src/pages/notebookController/screens/server/useSpawnerNotebookModalState.ts
frontend/src/services/routeService.ts
frontend/src/utilities/notebookControllerUtils.ts
frontend/src/utilities/useWatchDashboardConfig.tsx
frontend/src/utilities/useWatchNotebooksForUsers.tsx
manifests/base/deployment.yaml

* [Add Route Security to some routes](https://github.com/opendatahub-io/odh-dashboard/pull/488) 
* [Fix issue with requesting kube resources](https://github.com/opendatahub-io/odh-dashboard/pull/501)
* [Secure all routes](https://github.com/opendatahub-io/odh-dashboard/pull/502)
* [Secure nb-events endpoint](https://github.com/opendatahub-io/odh-dashboard/pull/510)
* [Update the logic of getting and patching the route for notebook](https://github.com/opendatahub-io/odh-dashboard/pull/516/files)
* [Don't blanket allow reading of dashboard namespace](https://github.com/opendatahub-io/odh-dashboard/pull/519) 
* [Improve Admin Access & Disallow Outside Namespaces](https://github.com/opendatahub-io/odh-dashboard/pull/524)
* [Improve Admin Access & Disallow Outside …

V1.16 build

---

frontend/src/api/network/servingRuntimes.ts
frontend/src/k8sTypes.ts
frontend/src/pages/modelServing/screens/const.ts
frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx
manifests/base/kustomization.yaml
manifests/base/model-serving-role-binding.yaml
manifests/base/model-serving-role.yaml
manifests/modelserving/kustomization.yaml
manifests/modelserving/servingruntimes-config.yaml

Add role for servingruntime configmap for https://issues.redhat.com/browse/RHODS-6330
1. Deploy all the files in the manifest folder
2. Create a new Model Server
3. Check that the ServingRuntime is created with the specification of the `servingruntimes-config` ConfigMap.
4. Now use #806 to fake a regular user.
5. Repeate the same process
6. Ensure regular user with no read options can access the manifest too

[UPSTREAM] Add dynamic spec to servingruntime objects

---

frontend/src/pages/modelServing/screens/const.ts

Fix issue with the deployed openvino image
Fix https://issues.redhat.com/browse/RHODS-6779
1. Create a cluster with pull secret to allow image fetching
2. Create a malformed servingruntime-config configmap
3. Create a new model serving and check the image is being pulled
You can check this too just doing podman pull registry.redhat.io/rhods/odh-openvino-servingruntime-rhel8@sha256:8af20e48bb480a7ba1ee1268a3cf0a507e05b256c5fcf988f8e4a3de8b87edc6

[UPSTREAM] Fix openvino image reference (#921)

---

backend/src/server.ts

https://issues.redhat.com/browse/RHOAIENG-4937

Add ca-bundle.crt to add cluster bundles into the dashboard

---

frontend/src/concepts/pipelines/apiHooks/usePipelines.ts
frontend/src/concepts/pipelines/context/PipelinesContext.tsx
frontend/src/pages/projects/screens/detail/overview/trainModels/PipelinesCard.tsx
frontend/src/pages/projects/screens/detail/overview/trainModels/PipelinesCardMetrics.tsx
frontend/src/pages/projects/screens/detail/overview/trainModels/PipelinesOverviewCard.tsx

https://issues.redhat.com/browse/RHOAIENG-5429

V2.22.0 fixes

---

backend/src/__tests__/objUtils.spec.ts
backend/src/routes/api/notebooks/utils.ts
backend/src/types.ts
backend/src/utils/notebookUtils.ts
backend/src/utils/objUtils.ts

https://issues.redhat.com/browse/RHOAIENG-5269

Fix cert jupyter notebooks

---

manifests/overlays/odhdashboardconfig/odhdashboardconfig.yaml

Fixes: [RHOAIENG-8521](https://issues.redhat.com/browse/RHOAIENG-8521)
Updates the dashboard config manifest file to enable the home page by default.

[RHOAIENG-8521] Enable home page in manifest file

---

frontend/.env

Catchup -- just the version number, used in segment. CI problems on Friday prevented this from getting in.

Upversion Dashboard (#3037) (#3043)

---

backend/src/utils/constants.ts
docs/dashboard-config.md
frontend/.env
frontend/src/pages/projects/screens/spawner/connections/ConnectionsFormSection.tsx
manifests/common/crd/odhdashboardconfigs.opendatahub.io.crd.yaml
manifests/rhoai/shared/odhdashboardconfig/odhdashboardconfig.yaml

* Upversion Dashboard
* Check and use response of connection saving (#3462)
(cherry picked from commit 4066b69c7d494f80c63ec11814a94707b9b1ee93)
* enable connection types by default (#3452)
(cherry picked from commit c575d1fc0bf5d2d31ea8fd1215a388a846640123)

Upversion dashboard (#3467)

---

Dockerfile.konflux

JIRA: https://issues.redhat.com/browse/RHOAIENG-17003
fixing the missing RHOAI logo when selecting dark mode on dashboard. 

[RHOAIENG-17003] Fixing missing RHOAI logo on dark mode.

---

Dockerfile.konflux

This pull request includes a minor change to the `Dockerfile.konflux`. The change removes the `--omit=optional` flag from the `npm ci` command, ensuring that optional dependencies are installed during the build process.
Carrying over https://github.com/red-hat-data-services/odh-dashboard/commit/f947d8c1dba84cd283508e5d98cbb60cc7ae63be 

Remove optional flag from npm ci command in konflux

---

.tekton/odh-dashboard-v2-24-push.yaml

retry konflux build due to RHOAIENG-31914
